name: node js ci 

on: 
    push:
        branches: [ main ]
 

jobs:
    bulid-test:
        runs-on: ubuntu-latest


        steps:
        - name: checkout code 
          uses: actions/checkout@v3

        - name: setting up node js 
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - run: npm install
        - run: npm test